# Generated by Django 5.2.12 on 2026-03-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasaber',
            options={'verbose_name': 'Área Saber'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='avaliacaotipo',
            options={'verbose_name': 'Avaliação tipo'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'verbose_name': 'Curso disciplina'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplinas', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='instituicaoensino',
            options={'verbose_name': 'Instituição de ensino'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
    ]
